SPHINXOPTS  ?=
SPHINXBUILD ?= sphinx-build
SOURCEDIR   = .
BUILDDIR    = build

.PHONY: all
all:
	$(SPHINXBUILD) -b html $(SOURCEDIR) $(SPHINXOPTS) $(BUILDDIR)

.PHONY: clean
clean:
	$(RM) -r $(BUILDDIR)

# vim:noet
